# Python Review 

Short review about some core concepts in Python exemplified by objects in the NUmpy Library.

Goals:

- recall basic Python vocabulary
- practice markdown syntax

## Libraries and packages

**library** is a collection of code that we can use to perform a specific task in our program. It can be a single file or multiple files.

**NumPy**

- core library for numerical computation
- many of the libraires use NumPy arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage

Lets import NumPy with its  **standard abbreviation** `np`:



In [1]:
import numpy as np

## Variables 

**variable** a name we assign to a particular object

Example:

In [2]:
#Assign a small array to a variable
a = np.array([[1,1,2], [3,5,8]])

In [3]:
a

array([[1, 1, 2],
       [3, 5, 8]])

## Convention: Use `snakecase` for naming variables

This is the naming convention we will be using in the course

**Remeber that variable names should be both descriptive and concise 

Recall:

Objects: data frame

Properties: number of rows, names of columns, dates created, etc
Actions: selecting from a dataframe

Variable is the name of a specific object

## Types

The **class** of an object and the **type** of an object refer to the same thing.

# See the type/class of a variable using the type function

numpy.ndarray

The numpy.ndarray is the core object/data type finder in the NumPy package

In [4]:
print(a[0,0])

1


In [5]:
type(a[0,0])

numpy.int64

`numpy.int64` is not the standard python integer type int

`numpy.int64` is a special data type in Numpy telling us that 1 is an integer stored as a 64-bit number

Check-in: access the value 5 in array 'a'


In [6]:
print(a[1,1])

5


## Functions

`print` was our first example of a **function** in Python

Functions take in a set of **arguments**, separated by commas, to create **outputs**

In this course, we will use the terms arguments and parameters interchangebly, but they do have a slight distinction

Using the `?` function to look into something, we obtain a **docstring**, which is basically the metadata of the function

Roughly speaking, a function has two types of arguments:

- **non-optional arguments**: arguments that *you* have to specify for the function to work

- **optional arguments**: arguments that are pre-filled with a default value, that can be overridden if desired.

Example:

`end` is a parameter in `print` with a default value on a new line
We can pass the value `:)` to this parameter so that it finished with this instead of a period

print('Change the end parameter', end= ':)')


## Attributed and methods

An object in Python has attributes and methods. 

- **attributes**: a property of an object
- **methods**: a function that acts on the object

## Check-in 

Make a diagram like the cat one, for a class `fish`. 

Example:

Numpy arrays have many methods and attributes. For example:



In [7]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [8]:
# T is an example of an attribute, which returns a transpose of array
print(a.T)

[[1 3]
 [1 5]
 [2 8]]


In [9]:
type(a.T)

numpy.ndarray

In [11]:
#shape is another attribute that tells us the shape of the array
print(a.shape)

(2, 3)


In [13]:
print('dim:', a.ndim, '|type:', type(a.ndim))

dim: 2 |type: <class 'int'>


In [14]:
#The min method returns the minimum value in the array that belongs to a specific axis

print(a)
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

Remember that methods are functions associated with an object. We can confirm this below:


In [15]:
a.tolist()

[[1, 1, 2], [3, 5, 8]]

In [18]:
type(a.tolist)

builtin_function_or_method

In [19]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



1.) optional argument (defaults to a space)


In [20]:
seventy_seven = 77

nintey_nine = '99'

In [21]:
type(seventy_seven)

int

In [22]:
type(nintey_nine)

str

In [26]:
print(seventy_seven, '%', nintey_nine, '%', seventy_seven, sep= '')

77%99%77
